/**
 * ⚠️ AUTO-GENERATED FILE
 * -----------------------
 * This file is generated automatically from the /messages directory.
 * Do NOT edit this file manually.
 * Any changes will be overwritten the next time the generator runs.
 */

export const defaultLocale = "en" as const;
export const baseLocales = ["en","de","fr","sw","es"] as const;
