/**
 * 🚨🚨 AUTO-GENERATED FILE 🚨🚨
 * -----------------------
 * This file is generated automatically from the /messages directory.
 * Do NOT edit this file manually.
 * Any changes will be overwritten the next time the generator runs.
 */

import { getLanguageName } from "./language";

const defaultLocale = "en" as const;
const locales = ["en","de","fr","sw","es"] as const;

if (!locales.includes(defaultLocale as Locale)) {
  throw new Error("defaultLocale must exist in locales");
}

export const i18n = {
  defaultLocale,
  locales,
} as const;

export type Locale = (typeof locales)[number];

export const languageNames = Object.fromEntries(
  i18n.locales.map((locale) => [locale, getLanguageName(locale)]),
) as Record<Locale, string>;
