import fs from "fs";
import path from "path";

const dir = path.join(process.cwd(), "messages");
const rawLocales = fs.readdirSync(dir).map((file) => file.replace(".json", ""));

const defaultLocale = "en";

const baseLocales = [
  defaultLocale,
  ...rawLocales.filter((l) => l !== defaultLocale),
];

const warning = `/**
 * ⚠️ AUTO-GENERATED FILE
 * -----------------------
 * This file is generated automatically from the /messages directory.
 * Do NOT edit this file manually.
 * Any changes will be overwritten the next time the generator runs.
 */`;

const content = `${warning}

export const defaultLocale = ${JSON.stringify(defaultLocale)} as const;
export const baseLocales = ${JSON.stringify(baseLocales)} as const;
`;

fs.writeFileSync("lib/generated-locales.ts", content);

console.log("[i18n] Default locale:", defaultLocale);
console.log("[i18n] Generated locales:", baseLocales);
