import fs from "fs";
import path from "path";

const dir = path.join(process.cwd(), "messages");

const rawLocales = fs.readdirSync(dir).map((file) => file.replace(".json", ""));

const defaultLocale = "en";

const locales = [
  defaultLocale,
  ...rawLocales.filter((l) => l !== defaultLocale),
];

const warning = `/**
 * 🚨🚨 AUTO-GENERATED FILE 🚨🚨
 * -----------------------
 * This file is generated automatically from the /messages directory.
 * Do NOT edit this file manually.
 * Any changes will be overwritten the next time the generator runs.
 */`;

const content = `${warning}

import { getLanguageName } from "@/lib/language";

const defaultLocale = ${JSON.stringify(defaultLocale)} as const;
const locales = ${JSON.stringify(locales)} as const;

if (!locales.includes(defaultLocale as Locale)) {
  throw new Error("defaultLocale must exist in locales");
}

export const i18n = {
  defaultLocale,
  locales,
} as const;

export type Locale = (typeof locales)[number];

export const languageNames = Object.fromEntries(
  i18n.locales.map((locale) => [locale, getLanguageName(locale)]),
) as Record<Locale, string>;
`;

fs.writeFileSync("i18n/config.ts", content);

console.log("[i18n] Default locale:", defaultLocale);
console.log("[i18n] Generated locales:", locales);
